language: node_js
node_js:
- 12
script:
- npm run build
- npm run lint

deploy:
    provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
        secure: jNhLR7dgCPLvLl2t7N09iafT3HGeTbhneGgHug3+Gogr1tTlJQjoAb6DP3kBvjvN04wJRyYlg9WQzlXHT2wwVse8ywjH17ytBAIvGKEU+S99Kpcs/yQaOKdfsIO28ot0dxP87ka8Tddd3qVWgVVC5rzKXf2pV3s9AOQ9j5gzS8PSfLc+Vgxm0PK3KznCDauRuE8ct2mLV8261aSjJIsGzm4WcAGlXRe+45uf2kjJb+ebcxCtyc4F08K43alFp/qWJXta7bVsQ0jjM3aMMWRRqdjmkKOQLxGkxIGh5p8i1jw6w5tm+3sdO46NxhgVdZLlSBnCOr80j/CX11sKNRGnXbLt4vq2g5NFNqlq22V6zB5nxGBuD3pZIR0hmHQytI9tNWUkC4M7HQPTTw2PrRLspzxNK2zZsd/ZGzVHvSH9NZVPxD5g08LJqvnW1LLs8Lc7pysYOvoijcI6oXKSG1VeFsBpi7IyDXhXiu2D9HXezpxjbfcuGlgXKvHYK6Hcb8dFo3V1qiOXiuiXV6Q+m0K987Juo40YpKd2X7SCqiwVztmh/U01jXOq66J30hHJnRST2upioOMtBUGu1G1F7Zrb3kdo7Xp9DbZzrg4SW+QajeqtY5q88HyuNDAovAIyARS/RzjCee4eWLDSh6ri2KkOM+qRRIW/QHTxHntBM1q4V38=
    on:
        tags: true
        repo: AckeeCZ/styleguide-backend-config
